/**
 * Remove all stop words from a string or array.
 *
 * @param string/array of words to check
 * @return string/array, return type dependent on input type
 */
var removeStopWords = function(words) {
  var cleanWords = [], inputString = false;

  // convert types between arrays & strings
  if (!$.isArray(words)) {
    words = words.split(' ');
    inputString = true;
  }
  // check each word against stopwords array
  jQuery.each(words, function(i, val) {
    val = jQuery.trim(val);
    if (  !isStopWord(val)
      ) {
      cleanWords.push(val);
    }
  });

  

  // if string was inputed, return a string
  if (inputString) {
    cleanWords = cleanWords.join(' ');
  }

  return cleanWords;
};

/**
 * Determine whether a word is a stopword or not.
 *
 * @param word to test
 * @return boolean
 */
var isStopWord = function(word) {
  word = jQuery.trim(word);
  return (jQuery.inArray(word, stopWords) > -1);
};

// var isIngredient= function(word) {
//   word = jQuery.trim(word);
//   return !(jQuery.inArray(word, stemmed_known_ingredients) > -1);
// };

// var isIngredient= function(word) {
//   _.mixin(_.str.exports()) ;
//   found1 =  _.find(stemmed_known_ingredients, function(ing){ 
//       return (_(word).startsWith(ing)  );
//    });
//   return found1;
// };
var isIngredient= function(word) {
  _.mixin(_.str.exports()) ;
  found1 =  _.find(stemmed_known_ingredients_from_flyers, function(ing){ 
      return (_(ing).startsWith(word)  );
   });
  return found1;
};

// var isIngredient= function(word) {
//   _.mixin(_.str.exports()) ;
//   found1 =  _.find(stemmed_known_ingredients, function(ing){ 
//       return (_(word).startsWith(ing)  );
//    });
//   found2 =  _.find(unstemmed_ing, function(ing){ 
//       return (_(ing).startsWith(word)  );
//    });
//   return (found1 || found2);
// };
var stemmed_known_ingredients_from_flyers = ["topround","greekyogurt","yogurt","chickendrumstick","chickenthigh","drumstick","thigh","snowcrab","salmonfillet","salmon","chickenbreast","porkloin","fryingchicken","bacon","cubesteak","turkeysausag","sausag","porkchop","groundturkei","sirloin","ribey","sirlointip","groundbeef","sirloinchop","hamsteak","frank","burger","kabob","bologna","kielbasa","shoulderroast","meatbal","nugget","pizza","pancak","frenchfri","bagel","icecream","pepperoni","provolon","roastbeef","rotisseriechicken","smokedturkeybreast","lobster","bologna","flatbread","ham","salad","feta","havarti","shrimp","cod","swai","flounder","scallop","haddock","cocktailshrimp","swordfish","scampi","crab","tilapia","muffin","scone","browni","tort","croissant","cupcak","cheesecak","cocacola","gatorad","salsa","pepsi","tomato","albacor","tuna","bean","egg","sourcream","strawberri","peach","lime","lemon","portabella","corn","tomato","avocado","greenbean","broccoli","carrot","romain"];

var stemmed_known_ingredients=["acidulatedwat","acke","acornsquash","agaragar","al","alfalfasprout","allspic","almond","almondess","almondextract","amaranth",
"amaretti","anchovi","anchovyess","angelica","angosturabitt","anis","appl","applechutnei","applejuic","applesauc","apricot","apricotjam","arborioric","arbroathsmoki",
"arganoil","arrowroot","artichok","asafoetida","asparagu","aubergin","avocado","bacon","bagel","baguett","bakedbean","bake","bakingpowd","balsamicvinegar","bambooshoot",
"banana","barbaryduck","barbecuesauc","barlei","basil","basmatiric","baybolet","bayleaf","bean","beansprout","bechamelsauc","beef","beefconsomm","beefconsomm","beefdrip",
"beefminc","beefrump","beefsausag","beefstock","beeftomato","beer","beetroot","berri","bestend","betelleav","beurremani","beurremani","bicarbonateofsoda","bilberri",
"birdseyechilli","biscotti","biscuit","blachan","blackbream","blackeyedbean","blackpepp","blackpud","blacksesamese","blacktreacl","blackbeansauc","blackberri","blackcurr",
"blackcurrantjuicedrink","blini","bloodorang","blueberri","boar","bokchoi","bonito","borag","borlottibean","bouquetgarni","braisingsteak","bramleyappl","bran","brandi",
"brandybutt","brandysnap","bratwurst","brazilnut","bread","breadrol","breadcrumb","breadfruit","breadnutse","breadstick","bresaola","brie","brill","brioch","brisket",
"broadbean","broccoli","broth","brownbread","brownlentil","brownric","brownsauc","brownshrimp","brownsugar","brusselssprout","buckwheat","buckwheatflour","bulgurwheat",
"bun","burger","butter","butterbean","buttercream","butterheadlettuc","buttermilk","butternutsquash",

"cabbag","caerphilli","cake","calasparraric","calvado","camembert","campagneloaf","candiedpeel","cannellinibean","capegooseberri","caper","capsicum","caramel","carawayse","cardamom",
"carob","carrageenmoss","carrot","cashew","cassava","castersugar","catfish","caulfat","cauliflow","cava","caviar","cavolonero","cayennepepp","celeriac","celeri","celeryse","champ",
"champagn","chanterellemushroom","chantillycream","chapatiflour","chapati","charcuteri","chard","charlottepotato","chayot","cheddar","chees","cheesesauc","cherri","cherrybrandi",
"cherrytomato","chervil","cheshir","chestnut","chestnutmushroom","chicken","chickenbreast","chickenleg","chickenliv","chickensoup","chickenstock","chickenthigh","chickenw","chickpea",
"chickpeaflour","chicori","chilli","chillioil","chillipast","chillipowd","chillisauc","chinesecabbag","chinesemushroom","chinesepancak","chipotl","chip","chive","chocol","chocolatebiscuit",
"chocolatebrowni","chocolatecak","chocolatemouss","chocolatetruffl","choppedtomato","chorizo","christmascak","christmaspud","chuckandblad","chump","chutnei","ciabatta","cider","cinnamon",
"citrusfruit","clam","clarifiedbutt","clementin","clottedcream","clove","cobnut","cockl","cocktail","cocoabutt","cocoapowd","coconut","coconutcream","coconutmilk","coconutoil","cod",
"codro","coffe","coffeebean","coffeeess","coffeegranul","coffeeliqueur","cognac","cola","coleslaw","colei","collar","compot","comt","condensedmilk","confectioneri","coriand",
"coriandercress","corianderse","cornoil","cornsyrup","cornedbeef","cornflour","coslettuc","cottagechees","couli","courgett","courtbouillon","couscou","couvertur","crab","crabappl",
"cracker","cranberri","cranberryjuic","cranberrysauc","crayfish","cream","creamchees","creamliqueur","creamoftartar","creamsoda","creamedcoconut","cremefraich","crepe","cress","crisp",
"croissant","crouton","crudit","crumbl","crystallisedging","cucumb","cumberlandsauc","cumin","curacao","curd","curdchees","curlykal","currantbread","currant","curri","curryleav",
"currypast","currypowd","custard","custardpowd","cuttlefish","dab","daikon","damson","dandelion","danishblu","darkchocol","date","demerarasugar","demiglacesauc","desiccatedcoconut",
"desire","digestivebiscuit","dijonmustard","dill","dimsumwrapp","dolcelatt","doublecream","doublegloucest","doversol","dragonfruit","driedapricot","driedcherri","driedchilli","driedfruit",
"driedmixedfruit","drysherri","duck","duckfat","dulcedelech","edam","eel","egg","eggliqueur","eggwash","eggwhit","eggyolk","elderberri","elderflow","emment","englishmuffin",
"englishmustard","escalop","evaporatedmilk","exoticfruit","farfal","fat","fennel","fennelse","fenugreek","feta","fettuccin","fieldmushroom","fig","filletofbeef","filopastri","fish",
"fishro","fishsauc","fivespicepowd","flageoletbean","flakedalmond","flakypastri","flank","flapjack","flatbread","flatbread","fleurdesel","flour","flourtortilla","flourypotato",
"flyingfish","focaccia","foiegra","fondant","fondantpotato","fontinachees","foodcolour","forcedrhubarb","fortifiedwin","fragrantric","frangipan","frankfurt","frenchbean","frenchbread",
"frenchdress","freshcoriand","freshtuna","fromagefrai","fruit","fruitbrandi","fruitcak","fruitjuic","fruitsalad","fudg","fusilli",
"galang","game","gammon","garammasala","garlic","garlicandherbcreamchees","garlicbread","gelatin","ghee","gherkin","giblet","gin","ginger","gingeral","gingerb","gingerbiscuit",
"gingerbread","glacecherri","globeartichok","glucos","gnocchi","goatschees","goatsmilk","goldensyrup","goos","goosefat","gooseberri","gorgonzola","gouda","grain","grapejuic","grapefruit",
"grapefruitjuic","grape","grapeseedoil","gratin","gravi","gravybrown","greenbanana","greenbean","greencabbag","greenlentil","greentea","greengag","greymullet","groundalmond","groundging",
"grous","gruyer","guacamol","guava","guineafowl","gurnard","habaerochilli","haddock","haggi","hake","halibut","halloumichees","ham","hare","haricotbean","harissa","hazelnut","hazelnutoil",
"heart","herballiqueur","herbaltea","herbesdeprov","herb","her","hogget","hoisinsauc","hoki","hollandaisesauc","homini","honei","honeycomb","horseradish","horseradishsauc","hotcrossbun",
"hummu","hunzaapricot","icecream","iceberglettuc","ic","icingsugar","irishstout","jaggeri","jam","japanesepumpkin","jelli","jerkseason","jerseyroyalpotato","jerusalemartichok","johndori",
"jujub","juniperberri","ju","kabana","kale","ketchup","ketjapmani","kidnei","kidneybean","kingedward","kipper","kirsch","kiwifruit","kohlrabi","lager","lamb","lambbreast","lambchop",
"lambfillet","lambkidnei","lambloin","lambminc","lambneck","lambrump","lambshank","lambshould","lambstock","lancashir","langoustin","lard","lardon","lasagn","lasagnesheet","laverbread",
"leek","legoflamb","lemon","lemonbalm","lemoncurd","lemonjuic","lemonsol","lemonad","lemongrass","lentil","lettuc","lime","limecordi","limejuic","limeleav","limepickl","ling","linguin",
"liqueur","liquoric","littlegemlettuc","liver","loafcak","lobster","loganberri","longgrainric","lovag","lyche",
"macadamia","macaroni","macaroon","mace","mackerel","madeira","madeiracak","madelein","maiz","maltedgrainbread","manchego","mandarin","mangetout","mango","mangochutnei","mangojuic",
"mangopickl","mangosteen","maplesyrup","margarin","marjoram","marmalad","marrow","marrowfatpea","marsalawin","marshmallow","marzipan","mascarpon","mashedpotato","matzo","mayonnais",
"medlar","megrim","melon","melonse","meringu","mesclun","milk","milkchocol","milkshak","millet","minc","mincepi","mincemeat","mint","mintsauc","mirepoix","mirin","miso","mixedberri",
"mixeddriedbean","mixedfish","mixednut","mixedspic","mixedspic","molass","monkfish","morel","mortadella","mozzarella","muesli","muffin","mulledwin","mungbean","mushroom","mussel",
"mustard","mustardcress","mustardleav","mustardoil","mustardpowd","mustardse","mutton","naanbread","nacho","nashi","nasturtium","nectarin","nettl","newpotato","nibbedalmond",
"noodlesoup","noodl","nori","nougat","nut","nutmeg","oatcak","oatmeal","oat","octopu","offal","oil","oilyfish","okra","oliv","oliveoil","onion","orang","orangejuic",
"orangeliqueur","oregano","ouzo","oxtail","oyster","oystermushroom","oystersauc","paella","pakchoi","palmsugar","pancak","pancetta","pandanleav","panetton","papaya",
"pappardel","paprika","parfait","parmesan","parslei","parsnip","partridg","passata","passionfruit","passionfruitjuic","pasta","pastrami","pastri","pasti","pate","pate",
"pawpaw","peashoot","peach","peanutbutt","peanutoil","peanut","pear","pearlbarlei","pea","pecan","pecorino","pectin","peel","penn","pepper","peppercorn","perch","perri",
"pesto","pheasant","piccalilli","pickl","pickledonion","pie","pigcheek","pigeon","pigeonpea","pike","pinenut","pineappl","pineapplejuic","pinkfirappl","pinkpeppercorn",
"pintobean","piripiri","pistachio","pittabread","pizza","plaic","plainflour","plantain","plum","polenta","pollack","pollock","pomegran","pomegranatejuic","pomelo","poppyse",
"porcini","pork","porkbelli","porkchop","porkfillet","porkleg","porkloin","porkminc","porksausag","porkshould","porksparerib","port","portobellomushroom","potato","potatowedg",
"poultri","poussin","pralin","prawn","prawncrack","preservedlemon","preserv","prosciutto","prune","prunejuic","puddingric","puffpastri","pumpernickelbread","pumpkin","pumpkinse",
"purplesproutingbroccoli","puylentil","quail","quailsegg","quatreepic","quinc","quinoa","rabbit","rackoflamb","radicchio","radish","rainbowchard","rainbowtrout","raisin","raita",
"rapeseedoil","raselhanout","raspberri","raspberryjam","ratafiabiscuit","ratatouil","redcabbag","redleicest","redlentil","redmullet","redonion","redric","redsnapp","redwin",
"redwinevinegar","redcurr","redcurrantjelli","rennet","rhubarb","ribofbeef","rice","riceflour","ricenoodl","ricepud","ricevinegar","ricewin","ricotta","rigatoni","risottoric",
"roastbeef","roastchicken","roastlamb","roastpork","roastpotato","roastturkei","rocksalmon","rocksalt","rocket","rootbeer","rootveget","roquefort","rosewin","rosemari","rosewat",
"rouill","royal","rum","rump","runnerbean","ryebread","ryeflour",
"saffloweroil","saffron","sage","salad","saladcream","saladleav","salami","salmon","salsa","salsifi","salt","saltbeef","saltcod","sambuca","samphir","sardin","satsuma","sauc","saucisson","sausag","savori","savoycabbag","scallop","scotchbonnetchilli","scrag","seabass","seabream","seasalt","seatrout","seafood","season","seawe","seed","selfraisingflour","semolina","serranoham","sesameoil","sesamese","sevilleorang","shallot","sharonfruit","shellfish","sherri","sherryvinegar","shiitakemushroom","shin","shortbread","shortcrustpastri","sichuanpepp","silversid","singlecream","sirloin","skate","sloe","sloegin","smokedchees","smokedfish","smokedhaddock","smokedmackerel","smokedsalmon","smokedtrout","snapper","sobanoodl","soda","sodabread","sole","sorbet","sorbet","sorrel","soup","sourdoughbread","souredcream","soysauc","soyabean","soyaflour",
"soyamilk","soyaoil","spaghetti","spaghettisquash","sparklingwin","specialitybread","spelt","speltflour","spice","spinach","splitpea","spongecak","springgreen","springonion",
"springrollwrapp","squash","squid","staranis","starfruit","steak","stemging","stewinglamb","stilton","stock","strawmushroom","strawberri","strawberryjam","stregaliqueur",
"strongwhiteflour","stuf","suet","sugar","sugarsnappea","sultana","sumac","summerfruit","sunfloweroil","sunflowerse","sushiric","swede","sweetpotato","sweetsherri",
"sweetbread","sweetcorn","swisschard","swissrollsandroulad","swordfish","syrup","tbonesteak","tabasco","taco","tagliatel","tahini","taleggio","tamari","tamarillo",
"tamarind","tangerin","tapenad","tapioca","taro","tarragon","tartaresauc","tayberri","tea","tequila","teriyakisauc","thaibasil","thyme","tilapia","tinnedtuna",
"toffe","tofu","tomato","tomatochutnei","tomatojuic","tomatopure","tongu","tonic","topsid","tortellini","tripe","trout","truffl","truffleoil","turbot","turkei",
"turkeybreast","turkeyminc","turkishdelight","turmer","turnip","vacherin","vanillaess","vanillaextract","vanillapod","veal","vegetableoil","vegetableshorten",
"vegetablestock","veget","vegetariansausag","venison","verju","vermicelli","vermouth","vineleav","vinegar","vodka","vodkacocktail","waffl","walnut","walnutoil",
"wasabi","waterchestnut","watercress","watermelon","waxypotato","webbslettuc","wensleydal","wheatgerm","whelk","whippingcream","whiski","whiskycocktail","whitebread",
"whitecabbag","whitechocol","whitefish","whitepepp","whitewin","whitewinevinegar","whitebait","whitecurr","white","wholegrainmustard","wholemealbread","wholemealflour",
"wildduck","wildgarl","wildmushroom","wildric","wine","winkl","woodpigeon","worcestershiresauc","yam","yeast","yellowlentil","yoghurt","zander","zest","zucchini"];

var known_ingredients=[
"acidulated water","ackee","acorn squash","agar-agar","ale","alfalfa sprouts","allspice","almond","almond essence",
"almond extract","amaranth","amaretti","anchovies","anchovy essence","angelica","angostura bitters","anise","apple",
"apple chutney","apple juice","apple sauce","apricot","apricot jam","arborio rice","arbroath smokie","argan oil",
"arrowroot","artichoke","asafoetida","asparagus","aubergine","avocado","bacon","bagel","baguette","baked beans",
"baking","baking powder","balsamic vinegar","bamboo shoots","banana","barbary duck","barbecue sauce","barley",
"basil","basmati rice","bay boletes","bay leaf","beans","beansprouts","béchamel sauce","beef","beef consommé","beef consomme",
"beef dripping","beef mince","beef rump","beef sausage","beef stock","beef tomato","beer","beetroot","berry","best end","betel leaves",
"beurre manie",
"beurre manié","bicarbonate of soda","bilberries","bird's-eye chillies","biscotti","biscuits","blachan","black bream",
"black eyed beans","black pepper","black pudding","black sesame seeds","black treacle","blackbean sauce","blackberry",
"blackcurrant","blackcurrant juice drink","blini","blood orange","blueberry","boar","bok choi","bonito","borage",
"borlotti beans","bouquet garni","braising steak","bramley apple","bran","brandy","brandy butter","brandy snaps",
"bratwurst","brazil nut","bread","bread roll","breadcrumbs","breadfruit","breadnut seeds","breadsticks","bresaola",
"brie","brill","brioche","brisket","broad beans","broccoli","broth","brown bread","brown lentil","brown rice","brown sauce",
"brown shrimp","brown sugar","brussels sprouts","buckwheat","buckwheat flour","bulgur wheat","buns","burger","butter",
"butter beans","buttercream icing","butterhead lettuce","buttermilk","butternut squash","cabbage","caerphilly","cake","calasparra rice",
"calvados","camembert","campagne loaf","candied peel","cannellini beans","cape gooseberries","capers","capsicum","caramel","caraway seeds",
"cardamom","carob","carrageen moss","carrot","cashew","cassava","caster sugar","catfish","caul fat","cauliflower","cava","caviar","cavolo nero",
"cayenne pepper","celeriac","celery","celery seeds","champ","champagne","chanterelle mushrooms","chantilly cream","chapati flour","chapatis",
"charcuterie","chard","charlotte potato","chayote","cheddar","cheese","cheese sauce","cherry","cherry brandy","cherry tomatoes","chervil","cheshire",
"chestnut","chestnut mushrooms","chicken","chicken breast","chicken leg","chicken liver","chicken soup","chicken stock","chicken thigh","chicken wing",
"chickpea","chickpea flour","chicory","chilli","chilli oil","chilli paste","chilli powder","chilli sauce","chinese cabbage","chinese mushrooms",
"chinese pancake","chipotle","chips","chives","chocolate","chocolate biscuit","chocolate brownies","chocolate cake","chocolate mousse",
"chocolate truffle","chopped tomatoes","chorizo","christmas cake","christmas pudding","chuck and blade","chump","chutney","ciabatta","cider",
"cinnamon","citrus fruit","clams","clarified butter","clementine","clotted cream","cloves","cobnut","cockles","cocktail","cocoa butter",
"cocoa powder","coconut","coconut cream","coconut milk","coconut oil","cod","cod roe","coffee","coffee beans","coffee essence","coffee granules",
"coffee liqueur","cognac","cola","coleslaw","coley","collar","compôte","comté","condensed milk",
"confectionery","coriander","coriander cress","coriander seeds","corn oil","corn syrup","corned beef","cornflour","cos lettuce","cottage cheese",
"coulis","courgette","court bouillon","couscous","couverture","crab","crab apple","crackers","cranberry","cranberry juice","cranberry sauce","crayfish",
"cream","cream cheese","cream liqueur","cream of tartar","cream soda","creamed coconut","crème fraîche","crêpe","cress","crisps","croissant","croûtons",
"crudités","crumble","crystallised ginger","cucumber","cumberland sauce","cumin","curacao","curd","curd cheese","curly kale","currant bread","currants","curry",
"curry leaves","curry paste","curry powder","custard","custard powder","cuttlefish","dab","daikon","damsons","dandelion","danish blue","dark chocolate","date",
"demerara sugar","demi-glace sauce","desiccated coconut","desirée","digestive biscuit","dijon mustard","dill","dim sum wrappers","dolcelatte","double cream",
"double gloucester","dover sole","dragon fruit","dried apricots","dried cherries","dried chilli","dried fruit","dried mixed fruit","dry sherry","duck","duck fat",
"dulce de leche","edam","eel","egg","egg liqueur","egg wash","egg white","egg yolk","elderberries","elderflower","emmental","english muffin","english mustard","escalope",
"evaporated milk","exotic fruit","farfalle","fat","fennel","fennel seeds","fenugreek","feta","fettuccine","field mushroom","fig","fillet of beef","filo pastry","fish",
"fish roe","fish sauce","five-spice powder","flageolet beans","flaked almonds","flaky pastry","flank","flapjacks","flatbread","flatbread","fleur de sel","flour",
"flour tortilla","floury potato","flying fish","focaccia","foie gras","fondant icing","fondant potatoes","fontina cheese","food colouring","forced rhubarb",
"fortified wine","fragrant rice","frangipane","frankfurter","french beans","french bread","french dressing","fresh coriander","fresh tuna","fromage frais",
"fruit","fruit brandy","fruit cake","fruit juice","fruit salad","fudge","fusilli","galangal","game","gammon","garam masala","garlic",
"garlic and herb cream cheese","garlic bread","gelatine","ghee","gherkin","giblets","gin","ginger","ginger ale","ginger beer","ginger biscuit",
"gingerbread",
"glacé cherries","globe artichoke","glucose","gnocchi","goats' cheese","goats' milk","golden syrup","goose","goose fat","gooseberry",
"gorgonzola","gouda","grain","grape juice","grapefruit","grapefruit juice","grapes","grapeseed oil","gratin","gravy","gravy browning",
"green banana","green beans","green cabbage","green lentil","green tea","greengages","grey mullet","ground almonds","ground ginger","grouse",
"gruyère","guacamole","guava","guinea fowl","gurnard","habañero chillies","haddock","haggis","hake","halibut","halloumi cheese","ham",
"hare","haricot beans","harissa","hazelnut","hazelnut oil","heart","herbal liqueur","herbal tea","herbes de provence","herbs","herring","hogget","hoisin sauce",
"hoki","hollandaise sauce","hominy","honey","honeycomb","horseradish","horseradish sauce","hot cross buns","hummus","hunza apricots","ice cream","iceberg lettuce",
"icing","icing sugar","irish stout","jaggery","jam","japanese pumpkin","jelly","jerk seasoning","jersey royal potatoes","jerusalem artichoke","john dory","jujube",
"juniper berries","jus","kabana","kale","ketchup","ketjap manis","kidney","kidney beans","king edward","kipper","kirsch","kiwi fruit","kohlrabi","lager","lamb",
"lamb breast","lamb chop","lamb fillet","lamb kidney","lamb loin","lamb mince","lamb neck","lamb rump","lamb shank","lamb shoulder","lamb stock","lancashire",
"langoustine","lard","lardons","lasagne","lasagne sheets","laverbread","leek","leg of lamb","lemon","lemon balm","lemon curd","lemon juice","lemon sole","lemonade",
"lemongrass","lentils","lettuce","lime","lime cordial","lime juice","lime leaves","lime pickle","ling","linguine","liqueur","liquorice","little gem lettuce","liver",
"loaf cake","lobster","loganberry","long-grain rice","lovage","lychee","macadamia","macaroni","macaroon","mace","mackerel","madeira","madeira cake","madeleines",
"maize","malted grain bread","manchego","mandarin","mangetout","mango","mango chutney","mango juice","mango pickle","mangosteen","maple syrup","margarine","marjoram",
"marmalade","marrow","marrowfat peas","marsala wine","marshmallow","marzipan","mascarpone","mashed potato","matzo","mayonnaise","medlars","megrim","melon","melon seeds",
"meringue","mesclun","milk","milk chocolate","milkshake","millet","mince","mince pies","mincemeat","mint","mint sauce","mirepoix","mirin","miso","mixed berries",
"mixed dried beans","mixed fish","mixed nuts","mixed spice","mixed spices","molasses","monkfish","morel","mortadella","mozzarella","muesli","muffins","mulled wine",
"mung beans","mushroom","mussels","mustard","mustard cress","mustard leaves","mustard oil","mustard powder","mustard seeds","mutton","naan bread","nachos","nashi",
"nasturtium","nectarine","nettle","new potatoes","nibbed almonds","noodle soup","noodles","nori","nougat","nut","nutmeg","oatcakes","oatmeal","oats","octopus","offal","oil",
"oily fish","okra","olive","olive oil","onion","orange","orange juice","orange liqueur","oregano","ouzo","oxtail","oyster","oyster mushrooms","oyster sauce","paella","pak choi",
"palm sugar","pancakes","pancetta","pandan leaves","panettone","papaya","pappardelle","paprika","parfait","parmesan","parsley","parsnip","partridge","passata","passion fruit",
"passion fruit juice","pasta","pastrami","pastry","pasty","pate","pâté","paw-paw","pea shoots","peach","peanut butter","peanut oil","peanuts","pear","pearl barley","peas","pecan",
"pecorino","pectin","peel","penne","pepper","peppercorn","perch","perry","pesto","pheasant","piccalilli","pickle","pickled onion","pie","pig cheeks","pigeon","pigeon peas",
"pike","pine nut","pineapple","pineapple juice","pink fir apple","pink peppercorn","pinto beans","piri-piri","pistachio","pitta bread","pizza","plaice","plain flour","plantain",
"plum","polenta","pollack","pollock","pomegranate","pomegranate juice","pomelo","poppy seeds","porcini","pork","pork belly","pork chop","pork fillet","pork leg","pork loin",
"pork mince","pork sausages","pork shoulder","pork spare rib","port","portobello mushrooms","potato","potato wedges","poultry","poussin","praline","prawn","prawn crackers",
"preserved lemons","preserves","prosciutto","prune","prune juice","pudding rice","puff pastry","pumpernickel bread","pumpkin","pumpkin seed","purple sprouting broccoli",
"puy lentil","quail","quail's egg","quatre-épices","quince","quinoa","rabbit","rack of lamb","radicchio","radish","rainbow chard","rainbow trout","raisins","raita",
"rapeseed oil","ras-el-hanout","raspberry","raspberry jam","ratafia biscuits","ratatouille","red cabbage","red leicester","red lentil","red mullet","red onion","red rice",
"red snapper","red wine","red wine vinegar","redcurrant","redcurrant jelly","rennet","rhubarb","rib of beef","rice","rice flour","rice noodles","rice pudding","rice vinegar",
"rice wine","ricotta","rigatoni","risotto rice","roast beef","roast chicken","roast lamb","roast pork","roast potatoes","roast turkey","rock salmon","rock salt","rocket",
"root beer","root vegetable","roquefort","rose wine","rosemary","rosewater","rouille","royal icing","rum","rump","runner beans","rye bread","rye flour","safflower oil",
"saffron","sage","salad","salad cream","salad leaves","salami","salmon","salsa","salsify","salt","salt beef","salt cod","sambuca","samphire","sardine","satsuma","sauces",
"saucisson","sausage","savory","savoy cabbage","scallop","scotch bonnet chilli","scrag","sea bass","sea bream","sea salt","sea trout","seafood","seasoning","seaweed","seeds",
"self-raising flour","semolina","serrano ham","sesame oil","sesame seeds","seville orange","shallot","sharon fruit","shellfish","sherry","sherry vinegar","shiitake mushroom",
"shin","shortbread","shortcrust pastry","sichuan pepper","silverside","single cream","sirloin","skate","sloe","sloe gin","smoked cheese","smoked fish","smoked haddock",
"smoked mackerel","smoked salmon","smoked trout","snapper","soba noodles","soda","soda bread","sole","sorbet","sorbet","sorrel","soup","sourdough bread","soured cream",
"soy sauce","soya beans","soya flour","soya milk","soya oil","spaghetti","spaghetti squash","sparkling wine","speciality bread","spelt","spelt flour","spices","spinach",
"split peas","sponge cake","spring greens","spring onion","spring roll wrappers","squash","squid","star anise","starfruit","steak","stem ginger","stewing lamb","stilton",
"stock","straw mushroom","strawberry","strawberry jam","strega liqueur","strong white flour","stuffing","suet","sugar","sugar-snap peas","sultanas","sumac","summer fruit",
"sunflower oil","sunflower seed","sushi rice","swede","sweet potato","sweet sherry","sweetbread","sweetcorn","swiss chard","swiss rolls and roulades","swordfish","syrup",
"t-bone steak","tabasco","taco","tagliatelle","tahini","taleggio","tamari","tamarillo","tamarind","tangerine","tapenade","tapioca","taro","tarragon","tartare sauce",
"tayberry","tea","tequila","teriyaki sauce","thai basil","thyme","tilapia","tinned tuna","toffee","tofu","tomato","tomato chutney","tomato juice","tomato purée",
"tongue","tonic","topside","tortellini","tripe","trout","truffle","truffle oil","turbot","turkey","turkey breast","turkey mince","turkish delight","turmeric","turnip",
"vacherin","vanilla essence","vanilla extract","vanilla pod","veal","vegetable oil","vegetable shortening","vegetable stock","vegetables","vegetarian sausage",
"venison","verjus","vermicelli","vermouth","vine leaves","vinegar","vodka","vodka cocktail","waffles","walnut","walnut oil","wasabi","water chestnut","watercress",
"watermelon","waxy potato","webbs lettuce","wensleydale","wheatgerm","whelk","whipping cream","whisky","whisky cocktail","white bread","white cabbage",
"white chocolate","white fish","white pepper","white wine","white wine vinegar","whitebait","whitecurrant","whiting","wholegrain mustard","wholemeal bread",
"wholemeal flour","wild duck","wild garlic","wild mushrooms","wild rice","wine","winkles","wood pigeon","worcestershire sauce","yam","yeast","yellow lentil",
"yoghurt","zander","zest","zucchini" ];

// list of words from: http://groups.drupal.org/node/16760
var stopWords = ['all','inrandom','respect','breakfast',
'auto','policyad','foodcom','collect','internet','trust','chef','world','searchi','freetak','tour','attr','desturl','recipesmi','public',
'privat','photo','crave','someth','sweet','savori',
'hearti','light','fit','wkplanhd','minheight','juici','photosour','cookbook','copycat','eat','tonight','restaur','similar','clone',
'store','forummi','menusal','picnicwow','friend','creativ','pick','partysumm','menusdinn','partyeasi','menusmenu','commun',
'forumsmi','topic','moremi','profilemi','contest','win','dream','trip','nycgiv','littl','french','chic','cocktail','hor','oeuvr',
'franc','prizesse','full','forumstop','qafood','blogmemb','supportal','toolssmal','freejoin','cooker','faqsour','onlin','box',
'sort','foodcomm','planningm','menuswint','weekli','tooljoin','usour','forum','hang','meet','trade','plai','gamesjoin','sifter','start',
'cuisin','occas','diet','filter','exclud','categori','narrow','match','updat','result','amount','satur','polyunsat','monounsat',
'fattran','protein','vitamin','calcium','iron','magnesium','alcohol','exactli','web','power','userinfo',
'ript','showfunct','inspir','boxand','live','discov','everydai','falsevar','enter','keyword','ifvalid',
'silent','term','word','onli','clubbest','everquick','easycook','schoolse',
'dairi','bread','life','simpler','hererecip','indexess','amanda','barnierth','kung','pao','berri','fool','easi','fooddinn','clubfood','club',
'product','secret','beat','heatbi','daniela','payneth','health','boot','campstyl','total','bodi','pink','urin','meansfre','love',
'social','lifewed','bui','giftbi','jen','familymom','gamesbi','carly','pregnant','react','toddler','temper',
'dog','pawsh','julia','mcewen','senior','beauti','fashion','editorth','creat','fishtail','braidfre','beautylif',
'elder','care','awardspet','kid','healthi','studybi','wendi','gravesth','save','electr','dure','yogafre','familypaw',
'craftskid','lisa','craft','edibl','flower','grow','homeplai','garden','blockfre','craftyy',
'scrollbox','molho','issuefil','select','edward','codeemail','issuein','usprivaci','send','simpl','weeknight','holidai','favastool','heart','brais','morejoin','maprss','daili','farerss','drinkrss','sister','miller','film','ride','lifecruis','travel','designhom','part','bonnier','epicurean','group','divis','reproduct','prohibit','jqueri','cooki','overrid','length','close','path',
'hidefunct','write','submit','flagid','limitnum','thelimit','charact','log','limit','subject','therul','usevar','error','null','moremost','random','link','camaro','amazonth','maraj','enjoi','advertis','todayg','giftrenew',
'item','casserol','combin','melt','chees','chamel','junejuli','neid','rigo',
'stori','passag','amazonrel','script','potyp','poasync','trueposrc','sfunction','lityp','liasync','lisrc',
'tbsp','minc','brazilian','italian','fry','stem','tsp','annatto','thai','anellini','toss','togeth','marin','meanwhil',
'set','asid','dent','saucepan','smooth','whisk','mediumlow','sauc','spread','bottom','repeat','omniprop','articl',
'saveur','jame','herbsth','american','spice','publish','nowmor','pizzaslay','valid','pleas','choos','accept',
'true','block','src','adtilenum','cript','href','target','blank','img','border','plugin','fals','advurl','alttext','dcgif','dcwmode','opaqu','imgurl','dcbgcolor','dcswf','dcminvers',
'shockwav','flash','object','nmd','check','number','player','minimum','nputypeof','oxnp','nmunm','return','trueels','iftypeof','vytryxnew','xoreturn','falseif','adcod','div',
'style','pxheight','classid','idflashad','param','namemovi','namequ','valuehigh','namewmod','emb','wmode','bgcolor','typeof','lta','gtltimg','uplog','homepagec','exclus',
'vegaslo','yorksan','findtool','drinkwin','drink','saveursit','lovein','magazin','closejul',
'usermi','alt','forksrat','fork','function','undefin','cachedf','els','glanc','main','chang','rail','owner','view','load','cours',
'coursei','popular','becaus','wai','moreif','bulb','crush','waterkosh','sea','slab','unslic','remov',
'inch','dice','seed','red','flake','yukon','gold','pei','allpurpos','peel','thick','juic','heavi','impract','devein',
'larger','recommend','split','lengthwis','refriger','frond','laci','top','coars','tough','outer','awai','core','highsid','saut',
'brown','aromat','bring','simmer','lightli','strain','quart','onc','render','increas','crisp','golden','pour','occasion','wooden','spoon',
'soften','bare','doesn','boil','vigor','thei','soft','firm','center','broth','hasn','thicken','smash','longer','releas','starch','reduc','cream','sit',
'finish','slow','tast','cool','bit','flavor','meld','reheat','don','ladl','evenli','lucki','abl','purchas','outstand','howev','goodqual','frozen','terrif','gener',
'wild','tiger','epicuri','gtltagt','epi','boxupload','outsav','review','favorit','sign','inget','norepeat','scroll','aseeital','heightpx','margin','widthpx','sponsor','posit','left','width',
'height','zindexget','iphon','exp','datevar','exptim','expgettim','var','bysync','inittim','valu','ccr','expir','issu','tablet','includ','applic',
'sale','tax','address','citi','state','jerseynew','mexiconew','yorknorth','aaapofpo','aeapofpo','mariana','ricou','virgin','email','policyord',
'outsid','search','chowder','jasper','pot','clam','corn','cndartcal','sponsorad','notesnew','notestab','recipebox','find','moreus','againus',
'fileprim','dpost','roastbi','viewprim','quit','simplist','entre','grand','reput','fact','coupl','tool','easier','event','mediumrar','uniform',
'cheaper','misread','churecip','caught','usda','prepar','special','discuss','forumbi','petrina','magic','compani','garam','discuss','forumbi',
'petrina','trim','common','grade','loose','receiv','refer','call','usual','small','chop','count','televis','current','slowcook','design',
'jeff','queri','geek','curiou','type','book','scienc','hack','real',
'good','simipli','home','show','custom','america','free','access','everi','showtri','dai','becom','member','classic','show',
'aadvertis','guarante','skin,','fill','dust','stack','instant','alert','servic','techniqu','tip','theme','thesi','smart','xlvi',
'wordpress','sell,','house','read','directioni','admin','goto','kitchenbi','feburari','share','thought','againi','lot','late','year',
'warm','cozi','mani','liquid','idea','big','comingi','fan','version','comment','post','food','blog','april','readi','bar','otherwis','lb','pound','info','avail','coat','cover','castiron','latin','market','print','bowl','powder','platter','rest','skillet','option','batch','crowd',
'mai','transfer','turn','uncov','materi','wedg','roughli','fine', 'percent','grate','inchvide', 'roast','drain','pit','toast','broil','rub','quarter','unsalt','brush','remain',
'understand','written','hundr','prior','constitut','cal','cach','agreement','site','user','registr','privaci','agre','polici','grubse','transmit','menu','backyard','distribut','reproduc',
'parti','recip','subscrib','permiss','ingredi','dividedkosh','shop','list','recipeview','pair','shop','rate','note','complet','guid','gear','great','plan','howto','plenti',
'nast','cond','epicuriouscom','veri','flaki','versatil','bon','app','tit','carefulli','dish','time','dry','freshli','scatter','fold','preheat','easili','mediumhigh','tightli',
'thinli','prinkl','sprinkl','paper','crookneck','digit','season','june','may','july','august','september','october','kitchen','heavyduti','easil','easy','hard','mixtur','yield','appetit','inc','befor','slide','nutrit','activ','ani','quick','quickdish','among','crimp','four','summer','winter','fall','spring','autum','halloween','christmas','meal','lunch','dinner','snack','pan','pattypan','wine','ground','hour','atop','analysi','provid','cut','fiber','steam','escap','larg','before','temperatur','continu','right','dri','plu','use','seal','crim','mistur','ounc','drizzl','surfac','work','altern','calori','form','edg','amoung','toothpick','oven','made','portion','place','stand','chill','room','ahead','equal','yellow','garnish','g','c','f','x','fat','all','rights','reserv','open','cook','slid','singl','build','fire','charcoal','doubl','divid','assort','ga','poke','water','salt','pepper','add','around','foil','side','test','taste','make','amoung','one','two','three','arrang','half','halv','leav','medium','fresh','heat','cold','layer','rim','serv','tablespoon','teaspoon','per','bake','grill','stir','parchment','thi','cup','sheet','slice','packet','thin','minut','second','let','oil','pepper','white','black',
  'a',
  'able',
  'about',
  'above',
  'abroad',
  'according',
  'accordingly',
  'across',
  'actually',
  'adj',
  'after',
  'afterwards',
  'again',
  'against',
  'ago',
  'ahead',
  'aint',
  'all',
  'allow',
  'allows',
  'almost',
  'alone',
  'along',
  'alongside',
  'already',
  'also',
  'although',
  'always',
  'am',
  'amid',
  'amidst',
  'among',
  'amongst',
  'an',
  'and',
  'another',
  'any',
  'anybody',
  'anyhow',
  'anyone',
  'anything',
  'anyway',
  'anyways',
  'anywhere',
  'apart',
  'appear',
  'appreciate',
  'appropriate',
  'are',
  'arent',
  'around',
  'as',
  'as',
  'aside',
  'ask',
  'asking',
  'associated',
  'at',
  'available',
  'away',
  'awfully',
  'b',
  'back',
  'backward',
  'backwards',
  'be',
  'became',
  'because',
  'become',
  'becomes',
  'becoming',
  'been',
  'before',
  'beforehand',
  'begin',
  'behind',
  'being',
  'believe',
  'below',
  'beside',
  'besides',
  'best',
  'better',
  'between',
  'beyond',
  'both',
  'brief',
  'but',
  'by',
  'c',
  'came',
  'can',
  'cannot',
  'cant',
  'cant',
  'caption',
  'cause',
  'causes',
  'certain',
  'certainly',
  'changes',
  'clearly',
  'cmon',
  'co',
  'co.',
  'com',
  'come',
  'comes',
  'concerning',
  'consequently',
  'consider',
  'considering',
  'contain',
  'containing',
  'contains',
  'corresponding',
  'could',
  'couldnt',
  'course',
  'cs',
  'currently',
  'd',
  'dare',
  'darent',
  'definitely',
  'described',
  'despite',
  'did',
  'didnt',
  'different',
  'directly',
  'do',
  'does',
  'doesnt',
  'doing',
  'done',
  'dont',
  'down',
  'downwards',
  'during',
  'e',
  'each',
  'edu',
  'eg',
  'eight',
  'eighty',
  'either',
  'else',
  'elsewhere',
  'end',
  'ending',
  'enough',
  'entirely',
  'especially',
  'et',
  'etc',
  'even',
  'ever',
  'evermore',
  'every',
  'everybody',
  'everyone',
  'everything',
  'everywhere',
  'ex',
  'exactly',
  'example',
  'except',
  'f',
  'fairly',
  'far',
  'farther',
  'few',
  'fewer',
  'fifth',
  'first',
  'five',
  'followed',
  'following',
  'follows',
  'for',
  'forever',
  'former',
  'formerly',
  'forth',
  'forward',
  'found',
  'four',
  'from',
  'further',
  'furthermore',
  'g',
  'get',
  'gets',
  'getting',
  'given',
  'gives',
  'go',
  'goes',
  'going',
  'gone',
  'got',
  'gotten',
  'greetings',
  'h',
  'had',
  'hadnt',
  'half',
  'happens',
  'hardly',
  'has',
  'hasnt',
  'have',
  'havent',
  'having',
  'he',
  'hed',
  'hell',
  'hello',
  'help',
  'hence',
  'her',
  'here',
  'hereafter',
  'hereby',
  'herein',
  'heres',
  'hereupon',
  'hers',
  'herself',
  'hes',
  'hi',
  'him',
  'himself',
  'his',
  'hither',
  'hopefully',
  'how',
  'howbeit',
  'however',
  'hundred',
  'i',
  'id',
  'ie',
  'if',
  'ignored',
  'ill',
  'im',
  'immediate',
  'in',
  'inasmuch',
  'inc',
  'inc.',
  'indeed',
  'indicate',
  'indicated',
  'indicates',
  'inner',
  'inside',
  'insofar',
  'instead',
  'into',
  'inward',
  'is',
  'isnt',
  'it',
  'itd',
  'itll',
  'its',
  'its',
  'itself',
  'ive',
  'j',
  'just',
  'k',
  'keep',
  'keeps',
  'kept',
  'know',
  'known',
  'knows',
  'l',
  'last',
  'lately',
  'later',
  'latter',
  'latterly',
  'least',
  'less',
  'lest',
  'let',
  'lets',
  'like',
  'liked',
  'likely',
  'likewise',
  'little',
  'look',
  'looking',
  'looks',
  'low',
  'lower',
  'ltd',
  'm',
  'made',
  'mainly',
  'make',
  'makes',
  'many',
  'may',
  'maybe',
  'maynt',
  'me',
  'mean',
  'meantime',
  'meanwhile',
  'merely',
  'might',
  'mightnt',
  'mine',
  'minus',
  'miss',
  'more',
  'moreover',
  'most',
  'mostly',
  'mr',
  'mrs',
  'much',
  'must',
  'mustnt',
  'my',
  'myself',
  'n',
  'name',
  'namely',
  'nd',
  'near',
  'nearly',
  'necessary',
  'need',
  'neednt',
  'needs',
  'neither',
  'never',
  'neverf',
  'neverless',
  'nevertheless',
  'new',
  'next',
  'nine',
  'ninety',
  'no',
  'nobody',
  'non',
  'none',
  'nonetheless',
  'noone',
  'no-one',
  'nor',
  'normally',
  'not',
  'nothing',
  'notwithstanding',
  'novel',
  'now',
  'nowhere',
  'o',
  'obviously',
  'of',
  'off',
  'often',
  'oh',
  'ok',
  'okay',
  'old',
  'on',
  'once',
  'one',
  'ones',
  'ones',
  'only',
  'onto',
  'opposite',
  'or',
  'other',
  'others',
  'otherwise',
  'ought',
  'oughtnt',
  'our',
  'ours',
  'ourselves',
  'out',
  'outside',
  'over',
  'overall',
  'own',
  'p',
  'particular',
  'particularly',
  'past',
  'per',
  'perhaps',
  'placed',
  'please',
  'plus',
  'possible',
  'presumably',
  'probably',
  'provided',
  'provides',
  'q',
  'que',
  'quite',
  'qv',
  'r',
  'rather',
  'rd',
  're',
  'really',
  'reasonably',
  'recent',
  'recently',
  'regarding',
  'regardless',
  'regards',
  'relatively',
  'respectively',
  'right',
  'round',
  's',
  'said',
  'same',
  'saw',
  'say',
  'saying',
  'says',
  'second',
  'secondly',
  'see',
  'seeing',
  'seem',
  'seemed',
  'seeming',
  'seems',
  'seen',
  'self',
  'selves',
  'sensible',
  'sent',
  'serious',
  'seriously',
  'seven',
  'several',
  'shall',
  'shant',
  'she',
  'shed',
  'shell',
  'shes',
  'should',
  'shouldnt',
  'since',
  'six',
  'so',
  'some',
  'somebody',
  'someday',
  'somehow',
  'someone',
  'something',
  'sometime',
  'sometimes',
  'somewhat',
  'somewhere',
  'soon',
  'sorry',
  'specified',
  'specify',
  'specifying',
  'still',
  'sub',
  'such',
  'sup',
  'sure',
  't',
  'take',
  'taken',
  'taking',
  'tell',
  'tends',
  'th',
  'than',
  'thank',
  'thanks',
  'thanx',
  'that',
  'thatll',
  'thats',
  'thats',
  'thatve',
  'the',
  'their',
  'theirs',
  'them',
  'themselves',
  'then',
  'thence',
  'there',
  'thereafter',
  'thereby',
  'thered',
  'therefore',
  'therein',
  'therell',
  'therere',
  'theres',
  'theres',
  'thereupon',
  'thereve',
  'these',
  'they',
  'theyd',
  'theyll',
  'theyre',
  'theyve',
  'thing',
  'things',
  'think',
  'third',
  'thirty',
  'this',
  'thorough',
  'thoroughly',
  'those',
  'though',
  'three',
  'through',
  'throughout',
  'thru',
  'thus',
  'till',
  'to',
  'together',
  'too',
  'took',
  'toward',
  'towards',
  'tried',
  'tries',
  'truly',
  'try',
  'trying',
  'ts',
  'twice',
  'two',
  'u',
  'un',
  'under',
  'underneath',
  'undoing',
  'unfortunately',
  'unless',
  'unlike',
  'unlikely',
  'until',
  'unto',
  'up',
  'upon',
  'upwards',
  'us',
  'use',
  'used',
  'useful',
  'uses',
  'using',
  'usually',
  'v',
  'value',
  'various',
  'versus',
  'very',
  'via',
  'viz',
  'vs',
  'w',
  'want',
  'wants',
  'was',
  'wasnt',
  'way',
  'we',
  'wed',
  'welcome',
  'well',
  'well',
  'went',
  'were',
  'were',
  'werent',
  'weve',
  'what',
  'whatever',
  'whatll',
  'whats',
  'whatve',
  'when',
  'whence',
  'whenever',
  'where',
  'whereafter',
  'whereas',
  'whereby',
  'wherein',
  'wheres',
  'whereupon',
  'wherever',
  'whether',
  'which',
  'whichever',
  'while',
  'whilst',
  'whither',
  'who',
  'whod',
  'whoever',
  'whole',
  'wholl',
  'whom',
  'whomever',
  'whos',
  'whose',
  'why',
  'will',
  'willing',
  'wish',
  'with',
  'within',
  'without',
  'wonder',
  'wont',
  'would',
  'wouldnt',
  'x',
  'y',
  'yes',
  'yet',
  'you',
  'youd',
  'youll',
  'your',
  'youre',
  'yours',
  'yourself',
  'yourselves',
  'youve',
  'z',
  'zero'
];

var get_stemmed_known_ingredients = function(){
  return stemmed_known_ingredients;
};

var get_known_ingredients = function(){
  return known_ingredients;
};

var get_stopWords = function(){
  return stopWords;
};